<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPHUBUDW2232" tests="5" failures="1" timestamp="6 Jun 2016 12:32:51 GMT" time="0.038" errors="0">
  <testcase name="stackFirstElement" time="0.0" classname="StackTest"/>
  <testcase name="stackFirstElement_Pop_checkSize" time="0.0" classname="StackTest"/>
  <testcase name="stackFirstElement_Pop_element" time="0.0" classname="StackTest"/>
  <testcase name="stackFirstElement_Pop_elementMultiple" time="0.0" classname="StackTest"/>
  <testcase name="stackFirstElement_Pop_failure" time="0.0" classname="StackTest">
    <failure type="org.testng.TestException" message="
Method StackTest.stackFirstElement_Pop_failure()[pri:0, instance:StackTest@419c5f1a] should have thrown an exception of type class javax.activity.InvalidActivityException">
      <![CDATA[org.testng.TestException: 
Method StackTest.stackFirstElement_Pop_failure()[pri:0, instance:StackTest@419c5f1a] should have thrown an exception of type class javax.activity.InvalidActivityException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1350)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:684)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- stackFirstElement_Pop_failure -->
</testsuite>
